### ISSUE TITLE
Neo4j java driver 5.13.0 gives `java.lang.NullPointerException: Cannot invoke "org.neo4j.driver.summary.InputPosition.line()" because "position" is null`

### ISSUE THREAD

**Issue by ellebrecht** [memgraph/memgraph#1520]
**Memgraph version**
Docker image memgraph/memgraph-platform:latest
v2.12.0+5~b2de962a3

**Environment**
Docker on amd64, Neo4j java driver 5.13.0

**Describe the bug**
When using Memgraph as the database for Spring Data Neo4j, simple operations like `Repository.count()` or `.findAll()` make the driver give an error: `java.lang.NullPointerException: Cannot invoke "org.neo4j.driver.summary.InputPosition.line()" because "position" is null`

**To Reproduce**
1. clone `https://github.com/ellebrecht/memgraph-spring-data-demo`
2. `mvnw spring-boot:build-image`
3. `docker compose up -d memgraph`
4. `docker compose up memgraph-spring-data-demo`

**Expected behavior**
For at least all basic use cases using Spring Data Neo4j, results should be equal to those given with Neo4j server.
To compare, use `docker compose up -d neo4j` instead on step 3.

This might be similar to [#2818](https://github.com/spring-projects/spring-data-neo4j/issues/2818). Even if the Neo4j java driver might not implement sufficient checks there, the issue does not occur with the same code running against Neo4j. So there should be a way for Memgraph to implement the same behaviour.

**Logs**
Memgraph server log:
```
2023-11-16 15:46:49,637 INFO Included extra file "/etc/supervisor/programs/lab.conf" during parsing
2023-11-16T15:46:49.637961403Z 2023-11-16 15:46:49,637 INFO Included extra file "/etc/supervisor/programs/memgraph.conf" during parsing
2023-11-16T15:46:49.637969303Z 2023-11-16 15:46:49,637 INFO Set uid to user 0 succeeded
2023-11-16T15:46:49.640469427Z 2023-11-16 15:46:49,640 INFO supervisord started with pid 1
2023-11-16T15:46:50.643605329Z 2023-11-16 15:46:50,643 INFO spawned: 'memgraph' with pid 7
2023-11-16T15:46:50.645676446Z 2023-11-16 15:46:50,645 INFO spawned: 'lab' with pid 8
2023-11-16T15:46:50.697331983Z You are running Memgraph v2.12.0+5~b2de962a3
2023-11-16T15:46:50.697375883Z To get started with Memgraph, visit https://memgr.ph/start
2023-11-16T15:46:51.585565388Z [2023-11-16 15:46:51.421] INFO: [lab] Lab is running at http://localhost:3000 in platform mode
2023-11-16T15:46:52.586755148Z 2023-11-16 15:46:52,586 INFO success: memgraph entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-11-16T15:46:52.586773249Z 2023-11-16 15:46:52,586 INFO success: lab entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-11-16T15:46:52.857858839Z <frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2023-11-16T15:46:54.461485090Z DGL backend not selected or invalid.  Assuming PyTorch for now.
```

Application log:
```
2023-11-16T15:47:00.819409904Z 2023-11-16T15:47:00.817Z  INFO 1 --- [           main] c.e.m.MemgraphDemoApplication            : Starting MemgraphDemoApplication v0.0.1-SNAPSHOT using Java 17.0.9 with PID 1 (/workspace/BOOT-INF/classes started by cnb in /workspace)
...
2023-11-16T15:47:02.945911127Z 2023-11-16T15:47:02.935Z  INFO 1 --- [           main] c.e.m.CommandLineAppStartupRunner        : Saved Entity(id=0, version=0, createdBy=default, createdDate=1700149622778, lastModifiedBy=default, lastModifiedDate=1700149622778, name=test678fa3c3-7860-4cb9-8153-0b903ff4abf3, props={key1=value1, key2=value2})
2023-11-16T15:47:02.947489938Z 2023-11-16T15:47:02.947Z TRACE 1 --- [           main] o.n.d.i.async.pool.ConnectionPoolImpl    : Acquiring a connection from pool towards db:7687
2023-11-16T15:47:02.951077264Z 2023-11-16T15:47:02.950Z DEBUG 1 --- [o4jDriverIO-2-2] o.n.d.i.async.pool.NettyChannelTracker   : Channel [0x047852a5] acquired from the pool. Local address: /172.21.0.3:59462, remote address: db/172.21.0.2:7687
2023-11-16T15:47:02.953032878Z 2023-11-16T15:47:02.952Z DEBUG 1 --- [o4jDriverIO-2-2] o.n.d.i.a.o.OutboundMessageHandler       : [0x047852a5][db:7687][bolt-1] C: BEGIN {mode="r", tx_metadata={app: "Java/17.0.9 (BellSoft OpenJDK 64-Bit Server VM 17.0.9+11-LTS) neo4j-java/5.13.0 spring-data/3.1.5 spring-data-neo4j/7.1.5"}, db="memgraph"}
2023-11-16T15:47:02.953448181Z 2023-11-16T15:47:02.953Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.a.o.OutboundMessageHandler       : [0x047852a5][db:7687][bolt-1] C: 00a2b111a3846d6f646581728b74785f6d65746164617461a183617070d0794a6176612f31372e302e39202842656c6c536f6674204f70656e4a444b2036342d4269742053657276657220564d2031372e302e392b31312d4c545329206e656f346a2d6a6176612f352e31332e3020737072696e672d646174612f332e312e3520737072696e672d646174612d6e656f346a2f372e312e35826462886d656d6772617068
2023-11-16T15:47:02.954691390Z 2023-11-16T15:47:02.954Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.async.inbound.ChunkDecoder       : [0x047852a5][db:7687][bolt-1] S: 0003b170a0
2023-11-16T15:47:02.954713290Z 2023-11-16T15:47:02.954Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.async.inbound.ChunkDecoder       : [0x047852a5][db:7687][bolt-1] S: 0000
2023-11-16T15:47:02.954886691Z 2023-11-16T15:47:02.954Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.a.inbound.InboundMessageHandler  : [0x047852a5][db:7687][bolt-1] S: b170a0
2023-11-16T15:47:02.955003892Z 2023-11-16T15:47:02.954Z DEBUG 1 --- [o4jDriverIO-2-2] o.n.d.i.a.i.InboundMessageDispatcher     : [0x047852a5][db:7687][bolt-1] S: SUCCESS {}
2023-11-16T15:47:02.971541411Z 2023-11-16T15:47:02.971Z DEBUG 1 --- [           main] org.springframework.data.neo4j.cypher    : Executing:
2023-11-16T15:47:02.971591411Z MATCH (entity:`Entity`) WITH entity, id(entity) AS __internalNeo4jId__, id(entity) AS __elementId__ RETURN count(*)
2023-11-16T15:47:02.972012114Z 2023-11-16T15:47:02.971Z DEBUG 1 --- [o4jDriverIO-2-2] o.n.d.i.a.o.OutboundMessageHandler       : [0x047852a5][db:7687][bolt-1] C: RUN "MATCH (entity:`Entity`) WITH entity, id(entity) AS __internalNeo4jId__, id(entity) AS __elementId__ RETURN count(*)" {} {}
2023-11-16T15:47:02.972360316Z 2023-11-16T15:47:02.972Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.a.o.OutboundMessageHandler       : [0x047852a5][db:7687][bolt-1] C: 0079b310d0734d415443482028656e746974793a60456e746974796029205749544820656e746974792c20696428656e7469747929204153205f5f696e7465726e616c4e656f346a49645f5f2c20696428656e7469747929204153205f5f656c656d656e7449645f5f2052455455524e20636f756e74282a29a0a0
2023-11-16T15:47:02.972455617Z 2023-11-16T15:47:02.972Z DEBUG 1 --- [o4jDriverIO-2-2] o.n.d.i.a.o.OutboundMessageHandler       : [0x047852a5][db:7687][bolt-1] C: PULL {n=1000}
2023-11-16T15:47:02.972623018Z 2023-11-16T15:47:02.972Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.a.o.OutboundMessageHandler       : [0x047852a5][db:7687][bolt-1] C: 0008b13fa1816ec903e8
2023-11-16T15:47:02.977316052Z 2023-11-16T15:47:02.976Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.async.inbound.ChunkDecoder       : [0x047852a5][db:7687][bolt-1] S: 0019b170a2866669656c64739188636f756e74282a298371696400
2023-11-16T15:47:02.977467253Z 2023-11-16T15:47:02.977Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.async.inbound.ChunkDecoder       : [0x047852a5][db:7687][bolt-1] S: 0000
2023-11-16T15:47:02.977937156Z 2023-11-16T15:47:02.977Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.a.inbound.InboundMessageHandler  : [0x047852a5][db:7687][bolt-1] S: b170a2866669656c64739188636f756e74282a298371696400
2023-11-16T15:47:02.978011057Z 2023-11-16T15:47:02.977Z DEBUG 1 --- [o4jDriverIO-2-2] o.n.d.i.a.i.InboundMessageDispatcher     : [0x047852a5][db:7687][bolt-1] S: SUCCESS {fields=["count(*)"], qid=0}
2023-11-16T15:47:02.978409360Z 2023-11-16T15:47:02.977Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.async.inbound.ChunkDecoder       : [0x047852a5][db:7687][bolt-1] S: 0004b1719101
2023-11-16T15:47:02.978425760Z 2023-11-16T15:47:02.978Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.async.inbound.ChunkDecoder       : [0x047852a5][db:7687][bolt-1] S: 0000
2023-11-16T15:47:02.978545761Z 2023-11-16T15:47:02.978Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.a.inbound.InboundMessageHandler  : [0x047852a5][db:7687][bolt-1] S: b1719101
2023-11-16T15:47:02.978656461Z 2023-11-16T15:47:02.978Z DEBUG 1 --- [o4jDriverIO-2-2] o.n.d.i.a.i.InboundMessageDispatcher     : [0x047852a5][db:7687][bolt-1] S: RECORD [1]
2023-11-16T15:47:02.979070864Z 2023-11-16T15:47:02.978Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.async.inbound.ChunkDecoder       : [0x047852a5][db:7687][bolt-1] S: 0171b170a98d636f73745f657374696d617465c14004000000000000826462886d656d6772617068886861735f6d6f7265c28d6e6f74696669636174696f6e7391a484636f64658b506c616e48696e74696e678b6465736372697074696f6e8088736576657269747984494e464f857469746c65d07e53657175656e7469616c207363616e2077696c6c2062652075736564206f6e2073796d626f6c2060656e746974796020616c74686f75676820746865726520697320612066696c746572206f6e206c6162656c73203a456e746974792e20436f6e7369646572206372656174696e672061206c6162656c20696e6465782e8c70617273696e675f74696d65c13f6d5c74751ce28fd013706c616e5f657865637574696f6e5f74696d65c13ef421f5f40d83768d706c616e6e696e675f74696d65c13f2cadc6de5c7d6b8672756e5f6964d02439656139623262352d396566302d346361662d383033312d65383739636537363635646284747970658172
2023-11-16T15:47:02.979095465Z 2023-11-16T15:47:02.978Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.async.inbound.ChunkDecoder       : [0x047852a5][db:7687][bolt-1] S: 0000
2023-11-16T15:47:02.979636069Z 2023-11-16T15:47:02.979Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.a.inbound.InboundMessageHandler  : [0x047852a5][db:7687][bolt-1] S: b170a98d636f73745f657374696d617465c14004000000000000826462886d656d6772617068886861735f6d6f7265c28d6e6f74696669636174696f6e7391a484636f64658b506c616e48696e74696e678b6465736372697074696f6e8088736576657269747984494e464f857469746c65d07e53657175656e7469616c207363616e2077696c6c2062652075736564206f6e2073796d626f6c2060656e746974796020616c74686f75676820746865726520697320612066696c746572206f6e206c6162656c73203a456e746974792e20436f6e7369646572206372656174696e672061206c6162656c20696e6465782e8c70617273696e675f74696d65c13f6d5c74751ce28fd013706c616e5f657865637574696f6e5f74696d65c13ef421f5f40d83768d706c616e6e696e675f74696d65c13f2cadc6de5c7d6b8672756e5f6964d02439656139623262352d396566302d346361662d383033312d65383739636537363635646284747970658172
2023-11-16T15:47:02.980803277Z 2023-11-16T15:47:02.980Z DEBUG 1 --- [o4jDriverIO-2-2] o.n.d.i.a.i.InboundMessageDispatcher     : [0x047852a5][db:7687][bolt-1] S: SUCCESS {planning_time=2.18802E-4, cost_estimate=2.5, plan_execution_time=1.92E-5, parsing_time=0.003584125, run_id="9ea9b2b5-9ef0-4caf-8031-e879ce7665db", has_more=FALSE, type="r", db="memgraph", notifications=[{severity: "INFO", description: "", code: "PlanHinting", title: "Sequential scan will be used on symbol `entity` although there is a filter on labels :Entity. Consider creating a label index."}]}
2023-11-16T15:47:02.987137622Z 2023-11-16T15:47:02.986Z  WARN 1 --- [           main] .n.c.Neo4jPersistenceExceptionTranslator : Don't know how to translate exception of type class java.lang.NullPointerException
2023-11-16T15:47:02.988849534Z 2023-11-16T15:47:02.988Z DEBUG 1 --- [o4jDriverIO-2-2] o.n.d.i.a.o.OutboundMessageHandler       : [0x047852a5][db:7687][bolt-1] C: ROLLBACK
2023-11-16T15:47:02.988986135Z 2023-11-16T15:47:02.988Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.a.o.OutboundMessageHandler       : [0x047852a5][db:7687][bolt-1] C: 0002b013
2023-11-16T15:47:02.989638040Z 2023-11-16T15:47:02.989Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.async.inbound.ChunkDecoder       : [0x047852a5][db:7687][bolt-1] S: 0003b170a0
2023-11-16T15:47:02.990251944Z 2023-11-16T15:47:02.989Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.async.inbound.ChunkDecoder       : [0x047852a5][db:7687][bolt-1] S: 0000
2023-11-16T15:47:02.990498446Z 2023-11-16T15:47:02.990Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.a.inbound.InboundMessageHandler  : [0x047852a5][db:7687][bolt-1] S: b170a0
2023-11-16T15:47:02.990569547Z 2023-11-16T15:47:02.990Z DEBUG 1 --- [o4jDriverIO-2-2] o.n.d.i.a.i.InboundMessageDispatcher     : [0x047852a5][db:7687][bolt-1] S: SUCCESS {}
2023-11-16T15:47:02.990978350Z 2023-11-16T15:47:02.990Z DEBUG 1 --- [o4jDriverIO-2-2] o.n.d.i.a.o.OutboundMessageHandler       : [0x047852a5][db:7687][bolt-1] C: RESET
2023-11-16T15:47:02.991043250Z 2023-11-16T15:47:02.990Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.a.o.OutboundMessageHandler       : [0x047852a5][db:7687][bolt-1] C: 0002b00f
2023-11-16T15:47:02.991633954Z 2023-11-16T15:47:02.991Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.async.inbound.ChunkDecoder       : [0x047852a5][db:7687][bolt-1] S: 0003b170a0
2023-11-16T15:47:02.991706555Z 2023-11-16T15:47:02.991Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.async.inbound.ChunkDecoder       : [0x047852a5][db:7687][bolt-1] S: 0000
2023-11-16T15:47:02.991880056Z 2023-11-16T15:47:02.991Z TRACE 1 --- [o4jDriverIO-2-2] o.n.d.i.a.inbound.InboundMessageHandler  : [0x047852a5][db:7687][bolt-1] S: b170a0
2023-11-16T15:47:02.991978157Z 2023-11-16T15:47:02.991Z DEBUG 1 --- [o4jDriverIO-2-2] o.n.d.i.a.i.InboundMessageDispatcher     : [0x047852a5][db:7687][bolt-1] S: SUCCESS {}
2023-11-16T15:47:02.992302059Z 2023-11-16T15:47:02.992Z DEBUG 1 --- [o4jDriverIO-2-2] o.n.d.i.async.pool.NettyChannelTracker   : Channel [0x047852a5] released back to the pool
2023-11-16T15:47:02.997619797Z 2023-11-16T15:47:02.993Z ERROR 1 --- [           main] c.e.m.CommandLineAppStartupRunner        : Count error
2023-11-16T15:47:02.997637397Z 
2023-11-16T15:47:02.997643197Z java.lang.NullPointerException: Cannot invoke "org.neo4j.driver.summary.InputPosition.line()" because "position" is null
2023-11-16T15:47:02.997649297Z 	at org.springframework.data.neo4j.core.ResultSummaries.format(ResultSummaries.java:120) ~[spring-data-neo4j-7.1.5.jar:7.1.5]
2023-11-16T15:47:02.997655497Z 	at org.springframework.data.neo4j.core.ResultSummaries.lambda$logNotifications$0(ResultSummaries.java:78) ~[spring-data-neo4j-7.1.5.jar:7.1.5]
2023-11-16T15:47:02.997660898Z 	at java.base/java.util.Collections$SingletonList.forEach(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997666098Z 	at org.springframework.data.neo4j.core.ResultSummaries.logNotifications(ResultSummaries.java:68) ~[spring-data-neo4j-7.1.5.jar:7.1.5]
2023-11-16T15:47:02.997671298Z 	at org.springframework.data.neo4j.core.ResultSummaries.process(ResultSummaries.java:55) ~[spring-data-neo4j-7.1.5.jar:7.1.5]
2023-11-16T15:47:02.997679998Z 	at org.springframework.data.neo4j.core.DefaultNeo4jClient$DefaultRecordFetchSpec.one(DefaultNeo4jClient.java:446) ~[spring-data-neo4j-7.1.5.jar:7.1.5]
2023-11-16T15:47:02.997686298Z 	at java.base/java.util.Optional.flatMap(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997689798Z 	at org.springframework.data.neo4j.core.Neo4jTemplate$DefaultExecutableQuery.getRequiredSingleResult(Neo4jTemplate.java:1133) ~[spring-data-neo4j-7.1.5.jar:7.1.5]
2023-11-16T15:47:02.997692998Z 	at org.springframework.data.neo4j.core.Neo4jTemplate.count(Neo4jTemplate.java:194) ~[spring-data-neo4j-7.1.5.jar:7.1.5]
2023-11-16T15:47:02.997695998Z 	at org.springframework.data.neo4j.core.Neo4jTemplate.count(Neo4jTemplate.java:181) ~[spring-data-neo4j-7.1.5.jar:7.1.5]
2023-11-16T15:47:02.997698998Z 	at org.springframework.data.neo4j.core.Neo4jTemplate.count(Neo4jTemplate.java:175) ~[spring-data-neo4j-7.1.5.jar:7.1.5]
2023-11-16T15:47:02.997702098Z 	at org.springframework.data.neo4j.core.Neo4jTemplate.count(Neo4jTemplate.java:170) ~[spring-data-neo4j-7.1.5.jar:7.1.5]
2023-11-16T15:47:02.997705098Z 	at org.springframework.data.neo4j.repository.support.SimpleNeo4jRepository.count(SimpleNeo4jRepository.java:107) ~[spring-data-neo4j-7.1.5.jar:7.1.5]
2023-11-16T15:47:02.997708198Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2023-11-16T15:47:02.997718598Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997724398Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997730598Z 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997738598Z 	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:288) ~[spring-data-commons-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997746098Z 	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136) ~[spring-data-commons-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997755098Z 	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120) ~[spring-data-commons-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997763298Z 	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516) ~[spring-data-commons-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997766998Z 	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285) ~[spring-data-commons-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997770098Z 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628) ~[spring-data-commons-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997773398Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.13.jar:6.0.13]
2023-11-16T15:47:02.997776498Z 	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:168) ~[spring-data-commons-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997779598Z 	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143) ~[spring-data-commons-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997782698Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.13.jar:6.0.13]
2023-11-16T15:47:02.997785798Z 	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:72) ~[spring-data-commons-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997789398Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.13.jar:6.0.13]
2023-11-16T15:47:02.997792498Z 	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.0.13.jar:6.0.13]
2023-11-16T15:47:02.997796799Z 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391) ~[spring-tx-6.0.13.jar:6.0.13]
2023-11-16T15:47:02.997802499Z 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.0.13.jar:6.0.13]
2023-11-16T15:47:02.997807199Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.13.jar:6.0.13]
2023-11-16T15:47:02.997817899Z 	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-6.0.13.jar:6.0.13]
2023-11-16T15:47:02.997823699Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.13.jar:6.0.13]
2023-11-16T15:47:02.997827899Z 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-6.0.13.jar:6.0.13]
2023-11-16T15:47:02.997831799Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.13.jar:6.0.13]
2023-11-16T15:47:02.997835499Z 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:244) ~[spring-aop-6.0.13.jar:6.0.13]
2023-11-16T15:47:02.997839999Z 	at jdk.proxy2/jdk.proxy2.$Proxy63.count(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997844599Z 	at com.ellebrecht.memgraphdemo.CommandLineAppStartupRunner.count(MemgraphDemoApplication.java:59) ~[classes/:0.0.1-SNAPSHOT]
2023-11-16T15:47:02.997850599Z 	at com.ellebrecht.memgraphdemo.CommandLineAppStartupRunner.run(MemgraphDemoApplication.java:41) ~[classes/:0.0.1-SNAPSHOT]
2023-11-16T15:47:02.997859899Z 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997866499Z 	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:755) ~[spring-boot-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997872299Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997877599Z 	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997885799Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997893599Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997898699Z 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997904099Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997909699Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997916299Z 	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997921599Z 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:750) ~[spring-boot-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997926799Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) ~[spring-boot-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997931899Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997940400Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.5.jar:3.1.5]
2023-11-16T15:47:02.997950800Z 	at com.ellebrecht.memgraphdemo.MemgraphDemoApplication.main(MemgraphDemoApplication.java:24) ~[classes/:0.0.1-SNAPSHOT]
2023-11-16T15:47:02.997954400Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2023-11-16T15:47:02.997957400Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997961800Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997966400Z 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
2023-11-16T15:47:02.997972300Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[workspace/:na]
2023-11-16T15:47:02.997980400Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[workspace/:na]
2023-11-16T15:47:02.997985600Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[workspace/:na]
2023-11-16T15:47:02.997990500Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[workspace/:na]
2023-11-16T15:47:02.997994600Z 
```

**Verification Environment**
memgraph-platform Docker image

**Comment by as51340** [comment]
@ellebrecht I think your github repo may be private because the link seems invalid, can you double check?

**Comment by ellebrecht** [comment]
With my PR at https://github.com/spring-projects/spring-data-neo4j/pull/2822 merged, the simple use cases demonstrated in the repo I mentioned now all work successfully. In my production application, more advanced use cases resulting in more complex queries still fail because of a lot of small details (quoting identifiers etc.).
If there is interest in taking memgraph to compatibility with Spring Data Neo4j, you could use my repo as a starting point for exploring. I suspect a number of small things would need to be fixed/generalized in SDN.

**Comment by as51340** [comment]
Happy to hear you are unblocked. If you stumble upon an issue, please let
me know.

Best regards,
Andi

pet, 24. stu 2023. u 09:37 Mario Ellebrecht ***@***.***>
napisao je:
