### ISSUE TITLE
Bug in "Memory control for detach delete" e2e test

### ISSUE THREAD

**Issue by antoniofilipovic** [memgraph/memgraph#1695]
**Memgraph version**
Master branch commit: [4ef6a1f](https://github.com/memgraph/memgraph/commit/4ef6a1f9c3c94afad405a358065ac3108491b0fe)

**Environment**
The bug also seen on CI: https://github.com/memgraph/memgraph/actions/runs/7812794569/job/21310558588?pr=1675

**Describe the bug**
E2E test fails:

```
Assertion failed in file /opt/actions-runner/_work/memgraph/memgraph/tests/e2e/memory/memory_limit_delete.cpp at line 77.
	Expression: 'false'
	Message: 'Query should have failed'
terminate called without an active exception
```

**To Reproduce**
Run e2e tests for memory

**Expected behavior**
Memory limit for detach delete should pass

**Logs**
```
INFO 2024-02-07 10:06:43,356 memgraph.tests.e2e] Memory control for detach delete STARTED.
Warning: 07 10:06:43.376] [warning] storage_parallel_index_recovery flag is deprecated. Check storage_mode_parallel_schema_recovery for more details.
Warning: 07 10:06:43.376] [warning] storage_parallel_index_recovery flag is deprecated. Check storage_mode_parallel_schema_recovery for more details.
You are running *** v2.14.0+20~62af92769
To get started with ***, visit https://memgr.ph/start
[2024-02-07 10:06:48.634] [stderr] [critical] 
Assertion failed in file /opt/actions-runner/_work/memgraph/memgraph/tests/e2e/memory/memory_limit_delete.cpp at line 77.
	Expression: 'false'
	Message: 'Query should have failed'
terminate called without an active exception
Traceback (most recent call last):
  File "runner.py", line 104, in <module>
    run(args)
  File "runner.py", line 78, in run
    subprocess.run([mg_test_binary] + workload["args"], check=True, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/actions-runner/_work/memgraph/memgraph/build/tests/e2e/memory/memgraph__e2e__memory__limit_delete', '--bolt-port', '[768](https://github.com/memgraph/memgraph/actions/runs/7812431668/job/21309456037?pr=1674#step:5:769)7']' died with <Signals.SIGABRT: 6>.
Error: Process completed with exit code 1.
```

**Comment by antepusic** [comment]
@antoniofilipovic Are you aware whether this issue still persists in testing?

**Comment by DavIvek** [comment]
Closing since we haven't seen this happen lately.
