### ISSUE TITLE
Compilation error when setting CMAKE_INSTALL_PREFIX to /usr

### ISSUE THREAD

**Issue by csqjxiao** [memgraph/memgraph#2130]
I checked out the v2.17.0 version of memgraph by the following command.
```bash
git clone -b v2.17.0  https://github.com/memgraph/memgraph
```

I tried to compile memgraph from source code on Ubuntu 24.04 (i.e., MacOS installed with lima and ubuntu-lts). The CPU chip on my computer is Apple M1 Pro with ARM instruction set.  

Then, I installed the dependencies by the following command and with toolchain-v5-binaries-ubuntu-24.04-arm64.
```bash
cd ~/memgraph
./init
```
Everything goes fine until this step.

Next, I configure the build system, by executing the following commands. Here, I changed the install cmake prefex to `/usr` instead of `/usr/local`.
```bash
mkdir -p build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr  ..
```

When I compile memgraph by the following
```bash
make memgraph
```
The building program reports the following error.
```bash
[100%] Linking CXX executable "../memgraph-2.17.0+33~78c2c8ce4_Debug"
Creating symlink to memgraph executable
Creating symlink for python_support
Generating memgraph configuration file
ERROR: failed validation of new value '/usr/lib/memgraph/query_modules' for flag 'query_modules_directory'
Traceback (most recent call last):
  File "/home/qingjunxiao.linux/memgraph/config/generate.py", line 110, in <module>
    flags = extract_flags(args.memgraph_binary)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qingjunxiao.linux/memgraph/config/generate.py", line 34, in extract_flags
    root = ET.fromstring(data)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/xml/etree/ElementTree.py", line 1336, in XML
    return parser.close()
           ^^^^^^^^^^^^^^
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
make[3]: *** [src/CMakeFiles/memgraph.dir/build.make:230: memgraph-2.17.0+33~78c2c8ce4_Debug] Error 1
make[3]: *** Deleting file 'memgraph-2.17.0+33~78c2c8ce4_Debug'
make[2]: *** [CMakeFiles/Makefile2:8424: src/CMakeFiles/memgraph.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:8431: src/CMakeFiles/memgraph.dir/rule] Error 2
make: *** [Makefile:1915: memgraph] Error 2
```

Can you help shed some light on how to solve this compilation problem? Great thanks

**Comment by gitbuda** [comment]
The compilation is almost finished, it might be that the memgraph binary is built, only the configuration file failed, it might be because:
* `memgraph` binary is faulty for some reason (maybe something wasn't initialized properly on ARM)

Could you run Memgraph by `cd build && ./memgraph`? What happens there?

**Comment by csqjxiao** [comment]
```bash
> The compilation is almost finished, it might be that the memgraph binary is built, only the configuration file failed, it might be because:
> 
> * `memgraph` binary is faulty for some reason (maybe something wasn't initialized properly on ARM)
> 
> Could you run Memgraph by `cd build && ./memgraph`? What happens there?

[ 97%] Built target mg-audit
[ 97%] Building CXX object src/glue/CMakeFiles/mg-glue.dir/auth.cpp.o
[ 97%] Building CXX object src/glue/CMakeFiles/mg-glue.dir/auth_checker.cpp.o
[ 97%] Building CXX object src/glue/CMakeFiles/mg-glue.dir/auth_handler.cpp.o
[ 97%] Building CXX object src/glue/CMakeFiles/mg-glue.dir/communication.cpp.o
[ 97%] Building CXX object src/glue/CMakeFiles/mg-glue.dir/SessionHL.cpp.o
[ 97%] Building CXX object src/glue/CMakeFiles/mg-glue.dir/ServerT.cpp.o
[ 97%] Building CXX object src/glue/CMakeFiles/mg-glue.dir/MonitoringServerT.cpp.o
[ 97%] Building CXX object src/glue/CMakeFiles/mg-glue.dir/run_id.cpp.o
[100%] Building CXX object src/glue/CMakeFiles/mg-glue.dir/query_user.cpp.o
[100%] Linking CXX static library libmg-glue.a
[100%] Built target mg-glue
[100%] Building CXX object src/CMakeFiles/memgraph.dir/memgraph.cpp.o
/home/qingjunxiao.linux/memgraph/src/memgraph.cpp:192:3: warning: 'Py_SetProgramName' is deprecated [-Wdeprecated-declarations]
  192 |   Py_SetProgramName(program_name);
      |   ^
/usr/include/python3.12/pylifecycle.h:37:1: note: 'Py_SetProgramName' has been explicitly marked deprecated here
   37 | Py_DEPRECATED(3.11) PyAPI_FUNC(void) Py_SetProgramName(const wchar_t *);
      | ^
/usr/include/python3.12/pyport.h:317:54: note: expanded from macro 'Py_DEPRECATED'
  317 | #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
      |                                                      ^
/home/qingjunxiao.linux/memgraph/src/memgraph.cpp:195:3: warning: 'PyEval_InitThreads' is deprecated [-Wdeprecated-declarations]
  195 |   PyEval_InitThreads();
      |   ^
/usr/include/python3.12/ceval.h:132:1: note: 'PyEval_InitThreads' has been explicitly marked deprecated here
  132 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
      | ^
/usr/include/python3.12/pyport.h:317:54: note: expanded from macro 'Py_DEPRECATED'
  317 | #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
      |                                                      ^
2 warnings generated.
[100%] Linking CXX executable "../memgraph-2.17.0+33~78c2c8ce4_Debug"
Creating symlink to memgraph executable
Creating symlink for python_support
Generating memgraph configuration file
ERROR: failed validation of new value '/usr/lib/memgraph/query_modules' for flag 'query_modules_directory'
Traceback (most recent call last):
  File "/home/qingjunxiao.linux/memgraph/config/generate.py", line 110, in <module>
    flags = extract_flags(args.memgraph_binary)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qingjunxiao.linux/memgraph/config/generate.py", line 34, in extract_flags
    root = ET.fromstring(data)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/xml/etree/ElementTree.py", line 1336, in XML
    return parser.close()
           ^^^^^^^^^^^^^^
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
make[3]: *** [src/CMakeFiles/memgraph.dir/build.make:230: memgraph-2.17.0+33~78c2c8ce4_Debug] Error 1
make[3]: *** Deleting file 'memgraph-2.17.0+33~78c2c8ce4_Debug'
make[2]: *** [CMakeFiles/Makefile2:8424: src/CMakeFiles/memgraph.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:8431: src/CMakeFiles/memgraph.dir/rule] Error 2
make: *** [Makefile:1915: memgraph] Error 2
$ ./memgraph
bash: ./memgraph: No such file or directory
$ ../memgraph-2.17.0+33~78c2c8ce4_Debug
bash: ../memgraph-2.17.0+33~78c2c8ce4_Debug: No such file or directory
```

During linking CXX executable "../memgraph-2.17.0+33~78c2c8ce4_Debug", because of the validation error, the build system delete the file 'memgraph-2.17.0+33~78c2c8ce4_Debug'.

**Comment by gitbuda** [comment]
@Darych I think you have a very similar setup, do you maybe have a clue what could be wrong?

@csqjxiao what is your Memgraph use-cause? How come you are trying to compile Memgraph from the source (I think this here is definitely possible to solve, but it's much easier to run Memgraph using already packaged binaries under https://memgraph.com/download)?

**Comment by csqjxiao** [comment]
> @Darych I think you have a very similar setup, do you maybe have a clue what could be wrong?
> 
> @csqjxiao what is your Memgraph use-cause? How come you are trying to compile Memgraph from the source (I think this here is definitely possible to solve, but it's much easier to run Memgraph using already packaged binaries under https://memgraph.com/download)?

OK, I walk around this problem by omitting the cmake flag `-DCMAKE_INSTALL_PREFIX=/usr`. After installing memgraph to the `/usr/local/lib/memgraph` directory, I create a symbolic link from `\usr\lib\memgraph` to `/usr/local/lib/memgraph`.
