### ISSUE TITLE
[BUG] documentation how-to-migrate-from-neo4j-to-memgraph neo4j docker command doesn't work

### ISSUE THREAD

**Issue by Firfi** [memgraph/memgraph#754]
**Memgraph version**
latest

**Environment**
Ventura 13.2, m1

**Describe the bug**

Running the neo4j command from the example https://memgraph.com/blog/how-to-migrate-from-neo4j-to-memgraph

```
docker run -p 7474:7474 -p 7687:7687 -v data_deleteme:/data -v  plugins_deleteme:/plugins --name neo4j-apoc -e NEO4J_apoc_export_file_enabled=true -e NEO4J_apoc_import_file_enabled=true -e NEO4J_apoc_import_file_use__neo4j__config=true -e NEO4JLABS_PLUGINS=\[\"apoc\"\] -e NEO4J_AUTH=neo4j/password --platform linux/arm64/v8 neo4j:latest
```

(note that I added `--platform linux/arm64/v8` as per the post and suffixed the volumes with `_deleteme` to make sure no clash with other local volumes there for sure)

gives the error

```
Applying default values for plugin apoc to neo4j.conf
java.lang.RuntimeException: java.io.IOException: No space left on device
	at org.neo4j.commandline.admin.security.SetInitialPasswordCommand.execute(SetInitialPasswordCommand.java:91)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:92)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.neo4j.cli.AdminTool.execute(AdminTool.java:94)
	at org.neo4j.cli.AdminTool.main(AdminTool.java:82)
Caused by: java.io.IOException: No space left on device
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:76)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:67)
	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288)
	at org.neo4j.io.fs.StoreFileChannel.write(StoreFileChannel.java:254)
	at org.neo4j.io.fs.StoreFileChannel.writeAll(StoreFileChannel.java:139)
	at org.neo4j.io.fs.DefaultFileSystemAbstraction$NativeByteBufferOutputStream.write(DefaultFileSystemAbstraction.java:281)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
	at org.neo4j.server.security.auth.FileRepositorySerializer.writeToFile(FileRepositorySerializer.java:45)
	at org.neo4j.server.security.auth.FileRepositorySerializer.saveRecordsToFile(FileRepositorySerializer.java:58)
	at org.neo4j.server.security.auth.FileUserRepository.persistUsers(FileUserRepository.java:91)
	at org.neo4j.server.security.auth.AbstractUserRepository.create(AbstractUserRepository.java:74)
	at org.neo4j.commandline.admin.security.SetInitialPasswordCommand.execute(SetInitialPasswordCommand.java:85)
	... 12 more
```

**To Reproduce**
1. Run `docker run -p 7474:7474 -p 7687:7687 -v data_deleteme:/data -v  plugins_deleteme:/plugins --name neo4j-apoc -e NEO4J_apoc_export_file_enabled=true -e NEO4J_apoc_import_file_enabled=true -e NEO4J_apoc_import_file_use__neo4j__config=true -e NEO4JLABS_PLUGINS=\[\"apoc\"\] -e NEO4J_AUTH=neo4j/password --platform linux/arm64/v8 neo4j:latest`

**Expected behavior**
It runs
**Logs**
Above

**Additional context**
I'm pretty sure I have a plenty of free space on my laptop.

**Comment by katarinasupe** [comment]
Hi @Firfi 👋  
As you said, it's maybe better to see on Neo4j GitHub why the above command is not working. It was working with previous versions of Neo4j (I think it was v4 then - should have used version instead of the latest tag, for sure 😓). If I discover something before you, I will also leave a comment here. Thank you for keeping us updated; it helps a lot 😄

**Comment by Firfi** [comment]
I realized it was my setup issue. It was indeed no space left [in whatever space is assigned to Docker], is just that touching a file was taking a little bit. docker purge / cleanup (images, volumes) did the job
